name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
       description: branch
       type: string
    
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug HEAD_REF
        run: echo "HEAD_REF is '${HEAD_REF}'"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          OUTPUT="$(bash -c "unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci --branches '${{github.event.input.branch}}'")"
          NEW_RELEASE_VERSION=$(echo "$OUTPUT" | grep -oP 'The next release version is \K(\d+\.\d+\.\d+)')
          echo "new-release-version=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
      - name: Use the version
        run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}" 