name: Release

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - beta
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug HEAD_REF
        run: echo "HEAD_REF is ${{ github.head_ref }}"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --dry-run --branches ${{github.head_ref}}
