name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy from
        type: string
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug HEAD_REF
        run: echo "HEAD_REF is '${HEAD_REF}'"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --dry-run --no-ci --branches ${{github.event.inputs.branch}}
