name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
       description: branch
       type: string
    
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug HEAD_REF
        run: echo "HEAD_REF is '${HEAD_REF}'"
      
      - name: Debug inputs
        run: echo "Input branch is '${{ github.event.inputs.branch }}'"

      - name: Release
        id: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          branch=${{ github.event.inputs.branch }}
          echo "Using branch: $branch"
          output=$(npx semantic-release --dry-run --no-ci --branches $branch)
          echo "$output"
          next_version=$(echo "$output" | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+')
          echo "$next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Use the version
        run: echo "The version is ${{ env.next-version }}"
